config/routes.rb
Abaktask::Application.routes.draw do
  root 'pages#index'

  get '/add', to: 'pages#new'
  get '/*slug/add', to: 'pages#new', as: :new_subpage
  get '/*slug/edit', to: 'pages#edit', as: :edit_subpage
  get '/*slug', to: 'pages#show', as: :subpage
  patch '/*slug', to: 'pages#update'
  put '/*slug', to: 'pages#update'

  resources :pages, path: "", path_names: { new: 'add' }, except: [:update]
end

app/models/page.rb
class Page < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  has_ancestry

  validates :name, presence: true, format: { with: /\A[а-яА-ЯёЁa-zA-Z0-9_]+\z/ }
  validates :title, presence: true
  validates :content, presence: true

  after_save :update_descendants_slugs

  def should_generate_new_friendly_id?
    name_changed?
  end

  private

  def update_descendants_slugs
    if has_children?
      descendants.each do |subpage|
        subpage.slug = [subpage.parent.slug, subpage.slug.split('/').last].join('/')
        subpage.save!
      end
    end
  end

  def add_parent_slug(slug_name)
    if has_parent?
      slug = [parent.slug, slug_name].join('/')
    else
      slug = slug_name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  def index
    @pages = Page.all
  end

  def show
  end

  def new
    @page = Page.new(parent_id: params[:parent_id])
  end

  def create
    @page = Page.new(page_params)

    if @page.save
      redirect_to subpage_path(@page)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @page.update(page_params)
      redirect_to subpage_path(@page)
    else
      render :edit
    end
  end

  private

  def set_page
    @page = Page.friendly.find(params[:slug])
  end

  def page_params
    params.require(:page).permit(:name, :title, :content, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def show_tree(page)
    tree = "<li>#{link_to page.name, subpage_path(page)}</li>"
    if page.has_children?
      tree += "<ul>"
      page.children.each do |page|
        tree += "#{show_tree(page)}"
      end
      tree += "</ul>"
    end
    tree.html_safe
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title>Abaktask</title>
 		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  		<%= csrf_meta_tags %>
  		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	</head>
	<body>

		<div class="container" style="margin-top: 30px;">
			<%= yield %>
		</div>


		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	</body>
</html>

app/views/pages/edit.html.erb
<div class="row">
	<div class="col-3"></div>

	<div class="col-6">
		<%= form_for @page do |f| %>

			<% if @page.errors.any? %>
				<% @page.errors.full_messages.each do |message| %>
					<div class="alert alert-danger" role="alert"><%= message %></div>
				<% end %>
			<% end %>

			<%= f.hidden_field :parent_id %>

			<h3>Name:</h3>
			<%= f.text_field :name %></br>
			
			<h3>Title:</h3>
			<%= f.text_field :title %></br>
			
			<h3>Content:</h3>
			<%= f.text_area :content %></br>
			
			<%= f.submit %>
		<% end %>	
		</br>
		<%= link_to 'Back', subpage_path(@page) %>
	</div>
	
	<div class="col-3"></div>
</div>

app/views/pages/index.html.erb
<div class="row">
	<div class="col-3"></div>

	<div class="col-6">
		<p>
  			<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    			Show tree
  			</a>
  		</p>

		<div class="collapse" id="collapseExample">
  			<div class="card card-body">
				<% @pages.roots.each do |page| %>
					<%= show_tree(page) %>
				<% end %>
			</div>
		</div>
		
		<%= link_to 'New page', new_page_path, class: 'btn btn-primary' %>
	</div>
	<div class="col-3"></div>
</div>

app/views/pages/new.html.erb
<div class="row">
	<div class="col-3"></div>

	<div class="col-6">
		<%= form_for @page do |f| %>

			<% if @page.errors.any? %>
				<% @page.errors.full_messages.each do |message| %>
					<div class="alert alert-danger" role="alert"><%= message %></div>
				<% end %>
			<% end %>

			<%= f.hidden_field :parent_id %>
			
			<h3>Name:</h3>
			<%= f.text_field :name %></br>

			<h3>Title:</h3>
			<%= f.text_field :title %></br>
			
			<h3>Content:</h3>
			<%= f.text_area :content %></br>

			<%= f.submit %>
		<% end %>	
		</br>
		<%= link_to 'Back', root_path, class: 'btn btn-primary' %>
	</div>
	<div class="col-3"></div>
</div>

app/views/pages/show.html.erb
<div class="row">
	<div class="col-3"></div>

	<div class="col-6">
		<p>
  			<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    			Show tree
  			</a>
  		</p>

		<div class="collapse" id="collapseExample">
  			<div class="card card-body">
    			<%= show_tree(@page) if @page.has_children? %>
  			</div>
		</div>

		<h1><%= @page.title %></h1>

        <p><%= @page.content %></p></br>

		<div class="btn-group" role="group">
			<%= link_to 'Add subpage', new_subpage_path(parent_id: @page.id), class: 'btn btn-primary' %>
			<%= link_to 'Update page', edit_subpage_path(@page), class: 'btn btn-primary' %>
			<%= link_to 'Main', pages_path, class: 'btn btn-primary' %>
		</div>
	</div>

	<div class="col-3"></div>
</div>